### PR TITLE
fix for latex commenting

### PR DESCRIPTION
**Pull request by djpaterson**
Issue #14 can be fixed by adding latex comments to the grammar as included in this patch

### CODE REVIEW

**Comment by redbassett** [comment]
Throw in a test for this comment style if you get the chance!

**Comment by redbassett** [comment]
Sorry for my previous rushed comment, here's a better one:

Thanks for your contribution! If possible, throw a test in to check this comment style, and add yourself as a thank you in the `humans.txt` file.

**Comment by djpaterson** [comment]
Sorry for the delay on this one, I didn't see that you had responded - I've added to the existing test for breaking comment lines. Hopefully the additions make it easier should more comment styles need to be added in the future. It is worth noting that the existing test was very sensitive to the comment style, because the line length met exactly the break point (i.e. '//' being two characters and '#' being one caused different outputs when wrapping), so I have changed this as well

**Review by redbassett — APPROVED** [review]
Looks good!

**Pull request merged**
